import {
  Button,
  Box,
  InputGroup,
  Input,
  InputRightElement,
  Icon,
  Text,
  Stack,
  SimpleGrid,
  Container,
} from "@chakra-ui/react";
import { Search2Icon, BellIcon, ArrowForwardIcon } from "@chakra-ui/icons";
import Head from "next/head";
import Latest from "@/components/Latest";
import Link from "next/link";
import { useState,useEffect } from "react";
import Cards1 from "@/components/Cards1";
import Slider from "react-slick";
import axios from "axios";
export default function Home({ news }) {

  const but = ["kamlesh","rohan","Healthy","Technology","Finance","Art","Sports","India","World"]

  const [butname,setButname] = useState('health')
  const [category,setCategory] = useState([])

  useEffect(() => {
   const fetchData = async () => {
      const result = await axios.get(`https://gnews.io/api/v4/search?q=%22${butname}%22&apikey=${process.env.NEXT_PUBLIC_API_KEY}`)
      setCategory(result.data.articles)
   }

    fetchData()
  }, [butname])

  const settings = {
    dots:false,
    infinite: true,
    speed:500,
    slidesToShow: 8,
    slidesToScroll: 3,
    responsive: [
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 2
      }
    }
  ]
  }

  return (
    <>
      <Head>
        <title>The Headliner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          margin={{
            base: "10px",
            md: "0 auto",
            lg: "0 auto",
            xl: "20px",
          }}
          display="flex"
          justifyContent="center"
          alignItems="center"
        >
          <InputGroup>
            <InputRightElement
              pointerEvents="none"
              children={<Search2Icon color="gray.300" />}
            />
            <Input
              bg="gray.100"
              borderRadius="20px"
              type="tel"
              placeholder="Doge coin to Moon.."
            />
          </InputGroup>
          <Icon
            margin={{
              base: "10px",
              md: "0 auto",
              lg: "0 auto",
              xl: "20px",
            }}
            color="white"
            bg="var(--button-color)"
            height="30px"
            width="30px"
            borderRadius="50%"
          >
            <BellIcon height="20px" width="20px" />
          </Icon>
        </Box>
        <Box
          display="flex"
          flexDirection="column"
          justifyContent="center"
          alignItems="center"
        >
          <Box
            w={{
              base: "80%",
              md: "90%",
              lg: "90%",
              xl: "80%",
            }}
            display="flex"
            justifyContent="space-between"
          >
            <Text
              fontSize={{
                base: "20px",
                md: "30px",
                lg: "30px",
                xl: "30px",
              }}
              fontWeight="bold"
              display="flex"
              justifyContent="space-between"
            >
              Latest News
            </Text>
            <Link href="/lstnews">
              <Text
                fontSize={{
                  base: "20px",
                  md: "20px",
                  lg: "20px",
                  xl: "20px",
                }}
                color="blue"
              >
                See All
                <ArrowForwardIcon />
              </Text>
            </Link>
          </Box>
        </Box>
        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          flexWrap="wrap"
        >
          <Box
            w={{
              base: "100%",
              md: "90%",
              lg: "90%",
              xl: "90%",
            }}
          >
            <Latest news={news} />
          </Box>
        </Box>
        <Box 
        marginTop={{
          base: "10px",
          xl: "20px",
        }}
        >
          <Slider {...settings}>
          {but.map((item) => (
            <div 
            style={{
              margin:"10px",
             width:"100px"
            }}
            >
            <Button
              key={item}
              variant="outline"
              borderRadius="20px"
              fontSize="15px"
              fontWeight="bold"

              _hover={{
                bg: "var(--button-color)",
                color: "white",
              }}
              _active={{
                bg: "var(--button-color)",
                color: "white",
              }}
           
              onClick={() => 
              setButname(item)
              }
            >
              {item}
            </Button>
            </div>
          ))}
          </Slider>
        </Box>
        <Box>
        <Container maxW="container.xl" mt="20px">
        <Text 
        fontSize={{
            base: "1.5rem",
            md: "2rem",
            lg: "2rem",
            xl: "2rem",
            }}
            fontWeight="bold"
            color="var(--primary-color)"
            mb="10px"
        >
            {butname} 
        </Text>
           <SimpleGrid columns={{
                base: 1,
                md: 2,
                lg: 3,
                xl: 4,
           }} spacingX='40px' spacingY='20px'>
                {category.map((item, index) => (
                    <Cards1 key={index} 
                    title={item.title}
                    image={item.image}
                    url={item.url}

                     />
                ))}
</SimpleGrid>
        </Container>
        </Box>
      </main>
    </>
  );
}

export async function getServerSideProps() {


  const res = await fetch(
    `https://gnews.io/api/v4/search?q=%22latest%20news%22&apikey=${process.env.NEXT_PUBLIC_API_KEY}`
  );
  const data = await res.json();
  return {
    props: {
      news: data,
    },
  };
}


